### ISSUE TITLE
investigate how to authenticate with gcloud sql

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-workspace#7] opened 2023-09-08 17:27 UTC
https://cloud.google.com/sql/docs/mysql/connect-auth-proxy

We need to be able to connect all our services to our databases - find out how.

**Comment by faucomte97** [comment] 2023-09-20 23:05
Duplicate of the admin task https://app.zenhub.com/workspaces/code-for-life-admin-5cf7f1b750c6a6242c50af4c/issues/gh/ocadotechnology/codeforlife-admin/875

**Closed by faucomte97** 2023-09-20 23:05 UTC
Labels: devops
